version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: payments_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - payments_network

  nginx:
    image: nginx:alpine
    container_name: payments_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - payments_network

  mysql:
    image: mysql:8.0
    container_name: payments_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: payments
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - payments_network

  redis:
    image: redis:7-alpine
    container_name: payments_redis
    ports:
      - "6379:6379"
    networks:
      - payments_network

  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: payments_worker
    working_dir: /var/www
    command: php artisan queue:work --tries=5 --backoff=10
    volumes:
      - .:/var/www
    depends_on:
      - app
      - redis
      - mysql
    networks:
      - payments_network

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: payments_scheduler
    working_dir: /var/www
    command: php artisan schedule:work
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - payments_network

volumes:
  mysql_data:

networks:
  payments_network:
